base/urls.py
from django.urls import path, include
from .views import home, Login, withdraw, referrals, logout_view, profile, how, tasks, signup, first_login, second_login, third_login, fourth_login, delete_withdrawal, index, ResetPasswordView, FileDownloadView, privacy
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy


app_name = 'base'

urlpatterns = [
    path('', index, name='index' ),
    path('register', signup, name='signup' ),
    path('login', Login, name='login' ),
    path('first_app', first_login, name='first-login' ),
    path('second_app', second_login, name='second-login' ),
    path('third_app', third_login, name='third-login' ),
    path('fourth_app', fourth_login, name='fourth-login' ),
    path('dashboard', home, name='home'),
    path('withdraw', withdraw, name='withdraw'),
    path('delete-withdrawal/<int:id>', delete_withdrawal, name='delete-withdraw'),
    path('referrals', referrals, name='referrals'),
    path('profile', profile, name='profile'),
    path('how', how, name='how'),
    path('tasks', tasks, name='tasks'),
    path('logout', logout_view, name='logout'),
    path('privacy', privacy, name='privacy'),
    path('password-reset', ResetPasswordView.as_view(), name='password-reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', success_url = reverse_lazy('base:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
    
    
    path('download/<str:file_name>/', FileDownloadView.as_view(), name='file_download'),

]

referral/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/auth/', include('authentication.urls')),
    path('', include('base.urls')),


    path("__reload__/", include("django_browser_reload.urls")),

]

admin.site.site_header = "Readershome Admin office"
admin.site.site_title = "Readershome Admin office"
admin.site.index_title = "Welcome to Readershome Admin office"

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/common/breadcrumbs.html
{% load static %}

<div class="breadcrumb-oitila db-breadcrumb">
    <div class="container">
        <div class="row justify-content-lg-around">
            <div class="col-xl-6 col-lg-7 col-md-5 col-sm-6 col-8">
                <div class="part-txt">
                    <h1>User Dashboard</h1>
                    {% comment %} <ul>
                        <li>home</li>
                        <li>{% block breadcrumb %}{% endblock breadcrumb %}</li>
                    </ul> {% endcomment %}
                </div>
            </div>

            {% if request.user %}
            
            <div class="col-xl-6 col-lg-5 col-md-7 col-sm-6 col-4 d-flex align-items-center">
                <div class="db-user-profile">
                    <div class="part-data">
                        <span class="name">{{ request.user }}
                            {% if request.user.is_vip %}
                            <span class="badge badge-success">VIP</span>
                            {% endif %}
                        </span>
                        <ul>
                            <li>
                                <span class="text">Balance</span>
                                <span class="number">₦ {{request.user.profile.account_balance}}</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            {% endif %}

        </div>
    </div>
</div>

templates/common/clock_header.html
<div class="top">
    
    <div class="container">
        <div class="row">
            <div class="col-xl-5 col-lg-3">
                <div class="welcome-text">
                    <p>Welcome to Readershome</p>
                </div>
            </div>
            <div class="col-xl-7 col-lg-9 d-xl-flex d-lg-flex d-block align-items-center">
                <div class="part-right">
                    <ul>
                        <li class="nav-item join-now-btn">
                            {% if messages %}
                                {% for message in messages %}
                                <div class="mb-0 text-center alert alert-dismissible fade show {{ message.extra_tags }}" role="alert">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                {% endfor %}
                            {% endif %} 
                        </li>
                        {% comment %} <li>
                            <span class="simple-text">Sever Time : </span>
                            <div class="server-time">
                                <div class="single-time clock-time">
                                    <span class="icon">
                                        <i class="far fa-clock"></i>
                                    </span>
                                    <span class="text">
                                        <span id="hours"></span>
                                        <span id="minutes"></span>
                                        <span id="seconds"></span>
                                    </span>
                                </div>
                                <div class="single-time">
                                    <span class="icon">
                                        <i class="fas fa-calendar-alt"></i>
                                    </span>
                                    <span class="text">
                                        <span id="date"></span>
                                        <span id="month"></span>
                                        <span id="year"></span>
                                    </span>
                                </div>
                            </div>
                        </li> {% endcomment %}
                        {% if not request.user.is_authenticated %}
                        <li>
                            <div class="user-panel">
                                <span>
                                    <a href="/" class="login-btn">Login</a>or</span><a href="#" class="register-btn">Register</a>
                                </div>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

templates/common/dashboard-menu.html
<div class="dashboard-menu">
    <nav>
        <ul>
            
            <li class="nav-item" id="nave">
               <a class="nav-link" href="/dashboard">Dashboard</a>
           </li>
            
            <li class="nav-item" id="nave">
                <a class="nav-link" href="/how">How to</a>
            </li>
            <li class="nav-item" id="nave">
                <a class="nav-link" href="/tasks">Tasks</a>
            </li>
            <li class="nav-item" id="nave">
                <a class="nav-link" href="/referrals">Referrals</a>
            </li>
            {% if request.user.is_authenticated %}
                {% if completed %}
                <li class="nav-item" id="nave" >
                    <a class="nav-link" href="/withdraw">Withdraw</a>
                </li>
                
                {% endif %}
                <li class="nav-item" id="nave">
                    <a class="nav-link" href="/profile">Profile</a>
                </li>

            {% endif %}
        </ul>
    </nav>
</div>


<script>

    const getPath = url => {
        const path = new URL(url).pathname
        const parts = path.split("/");
        return parts.length < 3 || !parts.includes("tag") ? parts[1] : parts[3]
      };
      
      const path = getPath(location.href); // getPath(location.href)
      
      $("#nave a").each(function() {
        const lnkPath = getPath($(this).prop("href"));
        $(this).toggleClass("active", path === lnkPath)
      })


</script>

templates/common/footer.html
{% load static %}

<div class="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-10">
                    <div class="about-widget">
                        <a href="/" class="logo">
                            <img src="{% static 'img/logo.png' %}" alt="">
                        </a>
                        <p>Download our apps,
                            We love to have you on board</p>
                        <div class="social-links">
                            <ul>
                                <li>
                                    <a href="https://www.facebook.com/www.readershome.ng/" class="single-link">
                                        <i class="fab fa-facebook-f"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://twitter.com/readershomeng" class="single-link">
                                        <i class="fab fa-twitter"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.instagram.com/readershome.ng/" class="single-link">
                                        <i class="fab fa-instagram"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://pinterest.com/rclaimreward/?actingBusinessid=884113108006790046" class="single-link">
                                        <i class="fab fa-pinterest-p"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <p>Follow Us</p>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-10">
                    <div class="link-widget">
                        <h4 class="title">
                            Useful links
                        </h4>
                        <ul>
                            <li>
                                <a href="/" class="single-link">
                                    About Us
                                </a>
                            </li>
                            <li>
                                <a href="/" class="single-link">
                                    Affiliate
                                </a>
                            </li>
                            <li>
                                <a href="/" class="single-link">
                                    Profit
                                </a>
                            </li>
                            <li>
                                <a href="/privacy" class="single-link">
                                    Terms & Policy
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="copyright-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-8 col-lg-8">
                    <p>Copyright © <a href="/">Readershome</a> - 2023. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </div>
</div>

templates/common/mobile_nav.html
{% load static %}

{% comment %} <div class="d-xl-none d-lg-none d-block">
    <div class="mobile-navigation-bar">
        <ul>
            <li>
                <a href="#0">
                    <img src="{% static 'img/svg/profile.svg' %}" alt="">
                </a>
            </li>
            <li>
                <a href="#0">
                    <img src="{% static 'img/svg/money-transfering.svg' %}" alt="">
                </a>
            </li>
            <li>
                <a href="#0">
                    <img src="{% static 'img/svg/calculator.svg' %}" alt="">
                </a>
            </li>
            <li>
                <a href="#header">
                    <img src="{% static 'img/svg/arrow.svg' %}" alt="">
                </a>
            </li>
        </ul>
    </div>
</div> {% endcomment %}

<div class="d-xl-block d-lg-block d-none">
    <div class="back-to-top-btn">
        <a href="#">
            <img src="{% static 'img/svg/arrow.svg' %}" alt="">
        </a>
    </div>
</div>

templates/common/second_header.html
{% load static %}

<div class="bottom">
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-xl-3 col-lg-2 d-xl-flex d-lg-flex d-block align-items-center">
                <div class="row">
                    <div class="col-4 d-xl-none d-lg-none d-block">
                        <button class="navbar-toggler" type="button">
                            <span class="dag"></span>
                            <span class="dag2"></span>
                            <span class="dag3"></span>
                        </button>    
                    </div>
                    <div class="col-xl-12 col-lg-12 col-8 d-xl-block d-lg-block d-flex align-items-center justify-content-end">
                        <div class="logo">
                            <a href="/">
                                <img src="{% static 'img/logo2.png' %}" alt="">
                            </a>
                        </div>

                        
                    </div>
                </div>
            </div>
            
            <div class="col-xl-9 col-lg-10">
                <div class="mainmenu">
                    <div class="d-xl-none d-lg-none d-block">
                        <div class="user-profile">
                            {% comment %} <div class="part-img">
                                <img src="{% static 'img/member-1.jpg' %}" alt="">
                            </div>
                            <div class="user-info">
                                <span class="user-name">Sadwel Eunton</span>
                                <span class="user-balance">Bal : $202.25</span>
                            </div> {% endcomment %}
                            <div class="log-out-area">
                                <a href="#">Log out</a>
                            </div>
                        </div>
                    </div>
                    <nav class="navbar navbar-expand-lg">              

                        <div class="collapse navbar-collapse {% if not request.user.is_authenticated %}py-3{% endif %}" id="navbarSupportedContent">
                            <ul class="navbar-nav ml-auto">
                                {% if not request.user.is_authenticated %}
                
                
                                {% comment %} <li class="nav-item dropdown show">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" id="homeDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Home
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="homeDropdown">
                                        <a class="dropdown-item" href="/">Homepage 01</a>
                                        <a class="dropdown-item" href="index-2.html">Homepage 02</a>
                                        <a class="dropdown-item" href="index-3.html">Homepage 03</a>
                                        <a class="dropdown-item" href="index-4.html">Homepage 04</a>
                                        <a class="dropdown-item" href="index-5.html">Homepage 05</a>
                                    </div>
                                </li> {% endcomment %}

                                {% comment %} <li class="nav-item">
                                    <a class="nav-link" href="about.html">about us<span class="sr-only">(current)</span></a>
                                </li>

                                <li class="nav-item dropdown show">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" id="db-Dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        dashboard
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="db-Dropdown">
                                        <a class="dropdown-item" href="dashboard.html">My account</a>
                                        <a class="dropdown-item" href="db-investment.html">Investment</a>
                                        <a class="dropdown-item" href="db-withdraw.html">Withdraw</a>
                                        <a class="dropdown-item" href="db-history.html">History</a>
                                        <a class="dropdown-item" href="db-referral.html">Referrals</a>
                                        <a class="dropdown-item" href="db-settings.html">Settings</a>
                                    </div>
                                </li>

                                <li class="nav-item dropdown show">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" id="pagesDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        pages
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                                        <a class="dropdown-item" href="affiliate.html">Affiliate</a>
                                        <a class="dropdown-item" href="faq.html">Faq</a>
                                        <a class="dropdown-item" href="error.html">Error</a>
                                        <a class="dropdown-item" href="privacy-policy.html">privacy & policy</a>
                                        <a class="dropdown-item" href="transaction.html">transaction</a>
                                        <a class="dropdown-item" href="login.html">Login</a>
                                        <a class="dropdown-item" href="register.html">Register</a>
                                    </div>
                                </li>

                                <li class="nav-item dropdown show">
                                    <a class="nav-link dropdown-toggle" href="#" id="blogDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Blog
                                      </a>
                                    <div class="dropdown-menu" aria-labelledby="blogDropdown">
                                        <a class="dropdown-item" href="blog-1.html">Blog 01</a>
                                        <a class="dropdown-item" href="blog-2.html">Blog 02</a>
                                        <a class="dropdown-item" href="blog-3.html">Blog 03</a>
                                        <a class="dropdown-item" href="blog-4.html">Blog 04</a>
                                        <a class="dropdown-item" href="blog-details.html">Blog details 1</a>
                                        <a class="dropdown-item" href="blog-details-2.html">Blog details 2</a>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="contact.html">contact</a>
                                </li> {% endcomment %}
                                {% endif %}
                                
                                <li class="nav-item join-now-btn">
                                    {% if request.user.is_authenticated %}
                                    <a class="nav-link" href="{% url 'base:logout' %}">Log out</a>
                                    {% endif %} 
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

templates/common/user-statistics.html
{% load static %}

{% if request.user %}
<div class="user-statics">
    <div class="row">
        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
            <div class="single-statics">
                <div class="part-icon">
                    <img src="{% static 'img/icon/002-cash.png' %}" alt="">
                </div>
                <div class="part-info">
                    <span class="number">₦ {{ request.user.profile.account_balance }}</span>
                    <span class="text">Ultimate Balance</span>
                </div>
            </div>
        </div>
        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
            <div class="single-statics">
                <div class="part-icon">
                    <img src="{% static 'img/icon/003-credit-card.png' %}" alt="">
                </div>
                <div class="part-info">
                    <span class="number">₦ {{approved_withdrawals.amount__sum}}</span>
                    <span class="text">Total Payout</span>
                </div>
            </div>
        </div>
        {% comment %} <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
            <div class="single-statics">
                <div class="part-icon">
                    <img src="{% static '' %}img/icon/001-donation.png" alt="">
                </div>
                <div class="part-info">
                    <span class="number">$24k.00</span>
                    <span class="text">Deposits Total</span>
                </div>
            </div>
        </div> {% endcomment %}
        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
            <div class="single-statics">
                <div class="part-icon">
                    <img src="{% static 'img/icon/004-hourglass.png' %}" alt="">
                </div>
                <div class="part-info">
                    <span class="number">₦ {{ pending_withdrawals.amount__sum}}</span>
                    <span class="text">Pending Amount</span>
                </div>
            </div>
        </div>
        {% comment %} <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
            <div class="single-statics">
                <div class="part-icon">
                    <img src="{% static 'img/icon/005-percentage.png' %}" alt="">
                </div>
                <div class="part-info">
                    <span class="number">$465.00</span>
                    <span class="text">Interest Earn</span>
                </div>
            </div>
        </div> {% endcomment %}
        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
            <div class="single-statics">
                <div class="part-icon">
                    <img src="{% static 'img/icon/006-wage.png' %}" alt="">
                </div>
                <div class="part-info">
                    <span class="number">₦ {{refferals_earnings.amount__sum}}</span>
                    <span class="text">Total Earning</span>
                </div>
            </div>
        </div>
        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
            <div class="single-statics">
                <div class="part-icon">
                    <img src="{% static 'img/icon/007-referral.png' %}" alt="">
                </div>
                <div class="part-info">
                    <span class="number">₦ {{refferals_earnings.amount__sum}}</span>
                    <span class="text">Total Referral Earnings</span>
                </div>
            </div>
        </div>
        {% comment %} <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
            <div class="single-statics">
                <div class="part-icon">
                    <img src="{% static 'img/icon/008-transfer.png' %}" alt="">
                </div>
                <div class="part-info">
                    <span class="number">$534.00</span>
                    <span class="text">Fund Transfer</span>
                </div>
            </div>
        </div> {% endcomment %}
    </div>
</div>

{% endif %}