base/urls.py
from django.urls import path, include
from .views import home, Login, withdraw, referrals, logout_view, profile, how, tasks, signup, first_login, second_login, third_login, fourth_login, delete_withdrawal, index, ResetPasswordView, FileDownloadView, privacy
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy


app_name = 'base'

urlpatterns = [
    path('', index, name='index' ),
    path('register', signup, name='signup' ),
    path('login', Login, name='login' ),
    path('first_app', first_login, name='first-login' ),
    path('second_app', second_login, name='second-login' ),
    path('third_app', third_login, name='third-login' ),
    path('fourth_app', fourth_login, name='fourth-login' ),
    path('dashboard', home, name='home'),
    path('withdraw', withdraw, name='withdraw'),
    path('delete-withdrawal/<int:id>', delete_withdrawal, name='delete-withdraw'),
    path('referrals', referrals, name='referrals'),
    path('profile', profile, name='profile'),
    path('how', how, name='how'),
    path('tasks', tasks, name='tasks'),
    path('logout', logout_view, name='logout'),
    path('privacy', privacy, name='privacy'),
    path('password-reset', ResetPasswordView.as_view(), name='password-reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', success_url = reverse_lazy('base:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
    
    
    path('download/<str:file_name>/', FileDownloadView.as_view(), name='file_download'),

]

referral/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/auth/', include('authentication.urls')),
    path('', include('base.urls')),


    path("__reload__/", include("django_browser_reload.urls")),

]

admin.site.site_header = "Readershome Admin office"
admin.site.site_title = "Readershome Admin office"
admin.site.index_title = "Welcome to Readershome Admin office"

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models

# Create your models here.

class TimestampedModel(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        ordering = ['-created_at', '-updated_at']

base/views.py
from django.shortcuts import render, redirect
from account.models import Bank, Coupon, Referral, Transactions, UserProfile
from authentication.forms import BankForm, CouponForm, LoginForm, NewUserForm, WithdrawalForm
from django.contrib.auth import authenticate, login, logout
from django.db.models import Sum
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import FileResponse, HttpResponseNotFound
from django.shortcuts import get_object_or_404
from django.views import View
import os
from django.conf import settings



class successMessage(SuccessMessageMixin):
    
    def form_valid(self, form):
        response = super().form_valid(form)
        success_message = self.get_success_message(form.cleaned_data)
        if success_message:
            messages.success(self.request, success_message, extra_tags='alert alert-success')
        return response
    

# Create your views here.

class ResetPasswordView(successMessage, PasswordResetView):
    template_name = 'password_reset.html'
    email_template_name = 'password_reset_email.html'
    subject_template_name = 'password_reset_subject.txt'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('base:login')
    
    
    
def index(request):
    context = {}
    return render(request,"home.html", context)
def Login(request):
    if request.user.is_authenticated:
        return redirect("base:home")
    login_form = LoginForm()
    if request.method == "POST":
        login_form = LoginForm(data=request.POST)
        if login_form.is_valid():
            email = request.POST["email"]
            password = request.POST["password"]
            user = authenticate(username=email, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    messages.success(request, "Login successful", extra_tags="alert-success")
                    return redirect('base:home')
                else:
                    messages.error(request, "Your account is not activated", extra_tags="alert-danger")
            else:
                messages.error(request, "Invalid email/password", extra_tags="alert-danger")
    context = {
        'form': login_form
    }
    return render(request,"login.html", context)


def first_login(request):
    if request.user.is_authenticated:
        return redirect("base:home")
    login_form = LoginForm()
    if request.method == "POST":
        login_form = LoginForm(data=request.POST)
        if login_form.is_valid():
            email = request.POST["email"]
            password = request.POST["password"]
            user = authenticate(username=email, password=password)
            if user:
                if user.is_active:
                    if user.first_app:
                        login(request, user)
                        messages.success(request, "Login successful", extra_tags="alert-success")
                        return redirect('base:home')
                    else:
                        user_profile = UserProfile.objects.get(user=user)
                        user_profile.account_balance += 500
                        user.first_app = True
                        user.save()
                        user_profile.save()
                        login(request, user)
                        messages.success(request, "Login successful", extra_tags="alert-success")
                        return redirect('base:home')
                else:
                    messages.error(request, "Your account is not activated", extra_tags="alert-danger")
            else:
                messages.error(request, "Invalid email/password", extra_tags="alert-danger")
    context = {
        'form': login_form
    }
    return render(request,"login.html", context)

def second_login(request):
    if request.user.is_authenticated:
        return redirect("base:home")
    login_form = LoginForm()
    if request.method == "POST":
        login_form = LoginForm(data=request.POST)
        if login_form.is_valid():
            email = request.POST["email"]
            password = request.POST["password"]
            user = authenticate(username=email, password=password)
            if user:
                if user.is_active:
                    if user.second_app:
                        login(request, user)
                        messages.success(request, "Login successful", extra_tags="alert-success")
                        return redirect('base:home')
                    else:
                        user_profile = UserProfile.objects.get(user=user)
                        user_profile.account_balance += 500
                        user.second_app = True
                        user.save()
                        user_profile.save()
                        login(request, user)
                        messages.success(request, "Login successful", extra_tags="alert-success")
                        return redirect('base:home')
                else:
                    messages.error(request, "Your account is not activated", extra_tags="alert-danger")
            else:
                messages.error(request, "Invalid email/password", extra_tags="alert-danger")
    context = {
        'form': login_form
    }
    return render(request,"login.html", context)

def third_login(request):
    if request.user.is_authenticated:
        return redirect("base:home")
    login_form = LoginForm()
    if request.method == "POST":
        login_form = LoginForm(data=request.POST)
        if login_form.is_valid():
            email = request.POST["email"]
            password = request.POST["password"]
            user = authenticate(username=email, password=password)
            if user:
                if user.is_active:
                    if user.third_app:
                        login(request, user)
                        messages.success(request, "Login successful", extra_tags="alert-success")
                        return redirect('base:home')
                    else:
                        user_profile = UserProfile.objects.get(user=user)
                        user_profile.account_balance += 500
                        user.third_app = True
                        user.save()
                        user_profile.save()
                        login(request, user)
                        messages.success(request, "Login successful", extra_tags="alert-success")
                        return redirect('base:home')
                else:
                    messages.error(request, "Your account is not activated", extra_tags="alert-danger")
            else:
                messages.error(request, "Invalid email/password", extra_tags="alert-danger")
    context = {
        'form': login_form
    }
    return render(request,"login.html", context)


def fourth_login(request):
    if request.user.is_authenticated:
        return redirect("base:home")
    login_form = LoginForm()
    if request.method == "POST":
        login_form = LoginForm(data=request.POST)
        if login_form.is_valid():
            email = request.POST["email"]
            password = request.POST["password"]
            user = authenticate(username=email, password=password)
            if user:
                if user.is_active:
                    if user.fourth_app:
                        login(request, user)
                        messages.success(request, "Login successful", extra_tags="alert-success")
                        return redirect('base:home')
                    else:
                        user_profile = UserProfile.objects.get(user=user)
                        user_profile.account_balance += 500
                        user.fourth_app = True
                        user.save()
                        user_profile.save()
                        login(request, user)
                        messages.success(request, "Login successful", extra_tags="alert-success")
                        return redirect('base:home')
                else:
                    messages.error(request, "Your account is not activated", extra_tags="alert-danger")
            else:
                messages.error(request, "Invalid email/password", extra_tags="alert-danger")
    context = {
        'form': login_form
    }
    return render(request,"login.html", context)

def signup(request):
    if request.user.is_authenticated:
        return redirect("base:home")
    refe = request.GET.get("ref")
    form = NewUserForm(initial={"referral_code": refe})

    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            try:
                user = form.save()
                reffered = UserProfile.objects.get(user=user)
                try:
                    ref_user = get_user_model().objects.get(username=refe)
                    try:
                        refferal = UserProfile.objects.get(user=ref_user)
                        Referral.objects.create(referrer=refferal, referred_user=reffered)
                        refferal.account_balance += 100
                        refferal.save()
                        Transactions.objects.create(user=get_user_model().objects.get(username=refe), type="R", amount=100, balance=refferal.account_balance)
                    except UserProfile.DoesNotExist:

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- breadcrumb end -->

<!-- account begin -->
<div class="user-dashboard">
    <div class="container">

        {% if request.user.is_vip %}
            <span class="badge badge-success">VIP</span>
        {% endif %}
        {% include "common/dashboard-menu.html" %}

        

        
        {% include "common/user-statistics.html" %}

        

        
    </div>
</div>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- breadcrumb begin -->
<div class="breadcrumb-oitila">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 col-lg-9 col-8">
                <div class="part-txt">
                    <h1>login</h1>
                    <ul>
                        <li>home</li>
                        <li>login page</li>
                    </ul>
                </div>
            </div>
            <div class="col-xl-3 col-lg-3 col-4 d-flex align-items-center">
                <div class="part-img">
                    <img src="{% static 'img/breadcrumb-img.png' %}" alt="image">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- breadcrumb end -->

<!-- login begin -->
<div class="login">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-8 col-lg-10 col-md-7 col-sm-9">
                <div class="form-area">
                    {% if form.errors %}
                        <div class="mb-0 w-full text-center alert alert-dismissible fade show alert-danger" role="alert">
                            {% for key, value in form.errors.items  %}
                            <span>{{ key }} : {{value}}</span>
                            {% endfor %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="row no-gutters">
                        <div class="col-xl-6 col-lg-6">
                            <div class="login-form">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Email address</label>
                                        {{form.email}}
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Password</label>
                                        {{form.password}}
                                    </div>
                                    <div class="form-group form-check">
                                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                        <label class="form-check-label" for="exampleCheck1">remember me</label>
                                        <button class="btn-form" type="submit">Submit</button>
                                    </div>
                                </form>
                                <div class="other-option">
                                    <a href="{% url 'base:signup' %}">register now</a>
                                    <a href="/password-reset">forgot password?</a>
                                </div>
                                
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 d-xl-block d-lg-block d-none">
                            <div class="blank-space"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- login end -->
{% endblock content %}


templates/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Readershome App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'base:password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  Readershome Team
{% endautoescape %}

templates/tasks.html

{% extends 'base.html' %}


{% block content %}

<div class="user-dashboard">
    <div class="container">

        {% include "common/dashboard-menu.html" %}

        
        {% comment %} {% include "common/user-statistics.html" %} {% endcomment %}

        <!-- account begin -->
        <h3 class="title">
            Download and Install our apps
        </h3>

        <div class="d-none">
            <div class="icon-completed">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 130.2 130.2">
                    <circle class="path circle" fill="none" stroke="#73AF55" stroke-width="6" stroke-miterlimit="10" cx="65.1" cy="65.1" r="62.1"></circle>
                    <polyline class="path check" fill="none" stroke="#73AF55" stroke-width="6" stroke-linecap="round" stroke-miterlimit="10" points="100.2,40.2 51.5,88.8 29.8,67.5 "></polyline>
                </svg>
            </div>
        </div>

        <div class="select-plan">
            <div class="row">
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-4">
                    <div class="single-plan">
                        <h3>Gameworld</h3>
                        {% comment %} <div class="plan-icon">
                            <img class="icon-img" src="assets/img/icon/bronze-medal.png" alt="">
                        </div>
                        <div class="price-info">
                            <span class="parcent">$10</span>
                            <span class="price">99%<small> || per month</small></span>
                        </div> {% endcomment %}
                        <a href="{% url 'base:file_download' file_name='Gameworld.apk' %}" class="btn-hyipox-medium price-button" download>Download</a>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-4">
                    <div class="single-plan">
                        <h3>Readershome-v-QuizTrivia</h3>
                        {% comment %} <div class="plan-icon">
                            <img class="icon-img" src="assets/img/icon/bronze-medal.png" alt="">
                        </div>
                        <div class="price-info">
                            <span class="parcent">$10</span>
                            <span class="price">99%<small> || per month</small></span>
                        </div> {% endcomment %}
                        <a href="{% url 'base:file_download' file_name='Readershome-v-QuizTrivia.apk' %}" class="btn-hyipox-medium price-button">Download</a>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-4">
                    <div class="single-plan">
                        <h3>Readershome Vintage Books</h3>
                        {% comment %} <div class="plan-icon">
                            <img class="icon-img" src="assets/img/icon/bronze-medal.png" alt="">
                        </div>
                        <div class="price-info">
                            <span class="parcent">$10</span>
                            <span class="price">99%<small> || per month</small></span>
                        </div> {% endcomment %}
                        <a href="{% url 'base:file_download' file_name='ReadershomeVintageBooks.apk' %}" class="btn-hyipox-medium price-button">Download</a>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-4">
                    <div class="single-plan">
                        <h3>Video Game Quiz</h3>
                        {% comment %} <div class="plan-icon">
                            <img class="icon-img" src="assets/img/icon/bronze-medal.png" alt="">
                        </div>
                        <div class="price-info">
                            <span class="parcent">$10</span>
                            <span class="price">99%<small> || per month</small></span>
                        </div> {% endcomment %}
                        <a href="{% url 'base:file_download' file_name='VideoGameQuiz.apk' %}" class="btn-hyipox-medium price-button">Download</a>
                    </div>
                </div>
                {% comment %} <div class="col-xl-3 col-lg-3 col-md-3 col-sm-4">
                    <div class="single-plan">
                        <h3>Basic Plan</h3>
                        <div class="plan-icon">
                            <img class="icon-img" src="assets/img/icon/bronze-medal.png" alt="">
                        </div>
                        <div class="price-info">
                            <span class="parcent">$10</span>
                            <span class="price">99%<small> || per month</small></span>
                        </div>
                        <a href="#" class="btn-hyipox-medium price-button">Invest now</a>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-4">
                    <div class="single-plan">
                        <h3>Basic Plan</h3>
                        <div class="plan-icon">
                            <img class="icon-img" src="assets/img/icon/bronze-medal.png" alt="">
                        </div>
                        <div class="price-info">
                            <span class="parcent">$10</span>
                            <span class="price">99%<small> || per month</small></span>
                        </div>
                        <a href="#" class="btn-hyipox-medium price-button">Invest now</a>
                    </div>
                </div> {% endcomment %}
            </div>
        </div>
        <!-- account end -->

    </div>
</div>
{% endblock content %}

templates/withdraw.html
{% extends 'base.html' %}

{% load static %}


{% block content %}

<div class="user-dashboard">
    <div class="container">

        {% include "common/dashboard-menu.html" %}

        
        {% comment %} {% include "common/user-statistics.html" %} {% endcomment %}

        <div class="withdraw-section">
            
            <div class="row">
                {% comment %} <div class="col-xl-5 col-lg-5 col-md-5">
                    <h3 class="title">
                        Add New Card
                    </h3>
                    <div class="add-credit-card card">
                        <div class="card-body">
                            <form>
                                <div class="row">
                                    <div class="col-xl-6 col-lg-6">
                                        <div class="form-group">
                                        <label for="exampleInputEmail1">Card Number</label>
                                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="•••• •••• •••• ••••">
                                        </div>
                                        <div class="form-group">
                                        <label for="exampleInputEmail4">Name on Card</label>
                                        <input type="email" class="form-control" id="exampleInputEmail4" aria-describedby="emailHelp" placeholder="Farzana Mukta">
                                        </div>
                                    </div>
                                    <div class="col-xl-6 col-lg-6">
                                        <div class="form-group expire-date-elem">
                                            <label for="inputDate">Expire date</label>
                                            <div class="form-row">
                                                <div class="form-group col-xl-6 col-lg-6 col-6">
                                                    <input type="text" class="form-control" id="inputdate" placeholder="MM">
                                                </div>
                                                <div class="form-group col-xl-6 col-lg-6 col-6">
                                                    <input type="text" class="form-control" id="inputZip" placeholder="YY">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail4">Card Code</label>
                                            <input type="email" class="form-control" id="exampleInputEmail4" aria-describedby="emailHelp" placeholder="CVC">
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn-hyipox-medium btn-add-new-card">Add New Account</button>
                            </form>
                        </div>
                    </div>
                </div> {% endcomment %}
                <div class="col-xl-12 col-lg-12 col-md-12">
                    <h3 class="title">
                        Withdraw Your Funds
                    </h3>

                    {% if not request.user.is_vip %}
                    <div>
                        
                        <form  method="POST">
                         {% csrf_token %}
 
                         {{coupon_form.code}}
                         <button type="submit" class="btn btn-secondary rounded my-3">Get VIP badge</button>
                        </form>
                     </div>
                    {% endif %}

                    <p>Purchase VIP badge coupons from our apps</p>
                    <p>Vip badge gets to withdaw and get paid 100% of their referral earnings</p>
                    <p>Non VIP gets paid 20%</p>
                    <form method="POST"> 
                        {% csrf_token %}
                    <div class="last-step">
                            <div class="payment-method-list row">

                                <div class="col-xl-6 col-lg-6 col-sm-12">
                                    <div class="oit-width-1">
                                        <label>Enter Your Amount</label>
                                            <span class="currency-symbol" id="basic-addon1">₦</span>
                                            {{ form.amount }}
                                            {% comment %} <input type="text" class="inputted-amount" value="10" /> {% endcomment %}
                                                
                                        <p>Minimum withdrawal: ₦4000</p>
                                        

                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-sm-12">
                                    <div class="available-balance-el">
                                        <span class="title">Balance</span>
                                        <ul>
                                            <li class="available">
                                                <span class="text">Available: </span>
                                                <span class="amount">₦{{request.user.profile.account_balance}}</span>
                                            </li>
                                            
                                        </ul>
                                        <button type="submit" class="btn-hyipox-medium withdraw-btn">Let's Withdraw</button>

                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="mt-4">
            <h3 class="title">
                Previous withdrawals
            </h3>
        </div>

        <div class="responsive">
            <table class="table table-bordered">
                <thead>
                    <th>ID</th>
                    <th>Date</th>
                    <th>Amount</th>
                    <th>Status</th>
                    <th>Action</th>
                </thead>
                <tbody>
                    {% for i in withdrawals %}
                    <tr>
                        <td>{{ i.id }}</td>
                        <td>{{ i.created_at }}</td>
                        <td>₦ {{ i.amount}}</td>
                        <td>
                            {% if i.status == "P" %}
                            <p class="badge badge-secondary">Pending</p>
                            {% elif i.status == "PC" %}
                            <p class="badge badge-warning">Processing</p>
                            {% elif i.status == "A" %}
                            <p class="badge badge-success">Approved</p>
                            {% elif i.status == "D" %}
                            <p class="badge badge-danger">Denied</p>
                            {% endif %}
                        </td>
                        <td>
                            {% if i.status == "P" %}
                                <a href="{% url 'base:delete-withdraw' i.id %}" class="btn btn-danger">Delete</a>
                            {% endif %}
                        </td>


                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</div>
{% endblock content %}